import { action, signal } from "./shared.mjs";

export default [
  {
    id: "pre-01",
    phase: "pre",
    category: "熟人帳號投票",
    platformStyle: "social",
    senderLabel: "同學小安",
    title: "可以幫我投票嗎？只差 3 票",
    message: "拜託現在幫我投一下，活動 10 分鐘後截止。點這個頁面登入社群帳號就可以投票。",
    correctJudgment: "risk",
    signalOptions: [
      signal("familiar", "訊息來自熟人帳號", "source"),
      signal("deadline", "用截止時間催促", "tactic"),
      signal("external-login", "要求到外部頁面登入", "action"),
      signal("casual-tone", "語氣像平常聊天", "source"),
    ],
    correctSignalIds: ["deadline", "external-login"],
    primarySignalId: "external-login",
    actionOptions: [
      action("open", "直接開連結登入投票", "unsafe"),
      action("reply", "回覆訊息詢問活動名稱", "neutral"),
      action("verify", "用原本的聯絡方式向同學確認，不點訊息內連結", "safe"),
      action("share", "把連結轉傳給其他同學", "unsafe"),
    ],
    correctActionIds: ["verify"],
    explanation: "熟人帳號也可能遭盜。真正需要先處理的是外部登入要求與限時壓力，而不是只看寄件人名字。",
    consequence: "若在假頁面登入，帳號與密碼可能被竊取，之後再冒用你聯絡其他人。",
    memoryTip: "熟人訊息也要走原聯絡方式確認。",
    officialVerification: "回到原社群 App 或用平常的電話、當面方式聯絡本人。",
    difficulty: 1,
  },
  {
    id: "pre-02",
    phase: "pre",
    category: "校園活動",
    platformStyle: "chat",
    senderLabel: "班級導師",
    title: "校慶志工集合提醒",
    message: "明天 07:40 在活動中心集合。名單與工作分配已放在學校原有的校務系統，請從校務 App 查看。",
    correctJudgment: "trusted",
    signalOptions: [
      signal("known-channel", "由平常使用的班級管道傳送", "source"),
      signal("official-app", "要求從既有校務 App 查看", "action"),
      signal("no-secret", "沒有要求密碼或付款", "money"),
      signal("morning", "集合時間很早", "tactic"),
    ],
    correctSignalIds: ["known-channel", "official-app", "no-secret"],
    primarySignalId: "official-app",
    actionOptions: [
      action("official", "自行開啟原有校務 App 核對", "safe"),
      action("ignore", "全部當成詐騙並封鎖導師", "unsafe"),
      action("forward", "把訊息轉到公開社群詢問", "neutral"),
      action("ask-password", "回覆自己的校務密碼請導師代查", "unsafe"),
    ],
    correctActionIds: ["official"],
    explanation: "訊息沒有帶外部登入連結，而是要求你自行開啟原本就使用的校務 App。這是較可信的查證路徑，但仍可自行核對。",
    consequence: "把所有正常通知都判成詐騙，可能錯失必要資訊，也會降低日後對警示的信任。",
    memoryTip: "較可信不等於完全安全，仍從原 App 核對。",
    officialVerification: "自行開啟學校原有校務 App，不透過訊息內新連結。",
    difficulty: 1,
  },
  {
    id: "pre-03",
    phase: "pre",
    category: "二手交易",
    platformStyle: "marketplace",
    senderLabel: "買家 Kevin",
    title: "平台顯示你沒開啟收款認證",
    message: "我已付款，但系統顯示你的帳戶沒認證。請加客服 LINE，照客服指示操作網銀才能完成收款。",
    correctJudgment: "risk",
    signalOptions: [
      signal("outside-platform", "要求離開交易平台加客服", "source"),
      signal("bank-operation", "要求操作網銀才能收款", "money"),
      signal("buyer-paid", "對方聲稱已付款", "tactic"),
      signal("product", "交易的是二手商品", "source"),
    ],
    correctSignalIds: ["outside-platform", "bank-operation", "buyer-paid"],
    primarySignalId: "bank-operation",
    actionOptions: [
      action("add-line", "加入客服 LINE 並照指示操作", "unsafe"),
      action("platform", "留在原平台查看訂單，從官方客服入口查證", "safe"),
      action("bank", "先提供銀行帳號與驗證碼", "unsafe"),
      action("discount", "改用更低價格成交", "neutral"),
    ],
    correctActionIds: ["platform"],
    explanation: "平台外客服與要求操作網銀，是典型高風險組合。收款不應需要依陌生客服指示操作轉帳或提供驗證碼。",
    consequence: "可能被誘導轉帳、解除分期或交出網銀驗證資訊。",
    memoryTip: "交易留在原平台，收款不靠陌生客服。",
    officialVerification: "自行進入交易平台訂單頁與官方客服中心查詢。",
    difficulty: 1,
  },
  {
    id: "pre-04",
    phase: "pre",
    category: "社團報名",
    platformStyle: "social",
    senderLabel: "校外青年志工團",
    title: "暑期志工名額剩最後 5 位",
    message: "填寫表單即可報名，需要姓名、手機、生日與家長聯絡方式。活動地點與主辦單位資訊會在錄取後公布。",
    correctJudgment: "insufficient",
    signalOptions: [
      signal("missing-organizer", "主辦單位與地點資訊不完整", "source"),
      signal("personal-data", "一開始就蒐集多項個資", "action"),
      signal("scarcity", "用名額稀缺催促", "tactic"),
      signal("volunteer", "活動是志工服務", "source"),
    ],
    correctSignalIds: ["missing-organizer", "personal-data", "scarcity"],
    primarySignalId: "missing-organizer",
    actionOptions: [
      action("submit", "先填資料搶名額", "unsafe"),
      action("verify-org", "先查主辦單位、活動地點與正式聯絡方式", "safe"),
      action("fake", "直接公開指控一定是詐騙", "neutral"),
      action("share", "轉傳給同學一起填", "unsafe"),
    ],
    correctActionIds: ["verify-org"],
    explanation: "資訊不足不代表一定是詐騙，但在主辦方、地點與用途不清楚時，不應先交出大量個資。",
    consequence: "若直接填寫，個資可能被濫用；若直接指控，也可能誤傷正常活動。",
    memoryTip: "資料不完整，先查來源再交資料。",
    officialVerification: "查詢主辦單位官網、正式電話與活動場地公開資訊。",
    difficulty: 2,
  }
];
