export const JUDGMENTS = ["risk", "insufficient", "trusted"];
export function safeDivide(numerator, denominator) { return denominator > 0 ? numerator / denominator : 0; }
export function median(values) { const nums=values.filter(Number.isFinite).toSorted((a,b)=>a-b); if(!nums.length)return 0; const mid=Math.floor(nums.length/2); return nums.length%2?nums[mid]:(nums[mid-1]+nums[mid])/2; }
export function signalScores(selectedIds=[],correctIds=[]) { const selected=new Set(selectedIds),correct=new Set(correctIds); let truePositive=0; for(const id of selected) if(correct.has(id)) truePositive+=1; const precision=safeDivide(truePositive,selected.size),recall=safeDivide(truePositive,correct.size); const f1=precision+recall>0?(2*precision*recall)/(precision+recall):0; return {precision,recall,f1}; }
export function recallByJudgment(responses=[]) { const recalls={}; for(const judgment of JUDGMENTS){const relevant=responses.filter((r)=>r.correctJudgment===judgment);const hits=relevant.filter((r)=>r.selectedJudgment===judgment).length;recalls[judgment]=safeDivide(hits,relevant.length);} return recalls; }
export function macroRecall(responses=[]) { const recalls=recallByJudgment(responses); return JUDGMENTS.reduce((sum,key)=>sum+recalls[key],0)/JUDGMENTS.length; }
export function actionAccuracy(responses=[]) { return safeDivide(responses.filter((r)=>r.isActionCorrect).length,responses.length); }
export function trustedFalsePositiveRate(responses=[]) { const trusted=responses.filter((r)=>r.correctJudgment==="trusted"); return safeDivide(trusted.filter((r)=>r.selectedJudgment==="risk").length,trusted.length); }
export function highConfidenceErrorRate(responses=[]) { const confident=responses.filter((r)=>Number(r.confidence)>=3); return safeDivide(confident.filter((r)=>!r.isJudgmentCorrect).length,confident.length); }
export function aggregateSignalScores(responses=[]) { if(!responses.length)return {precision:0,recall:0,f1:0}; const scores=responses.map((r)=>signalScores(r.selectedSignalIds,r.correctSignalIds)); return {precision:scores.reduce((s,x)=>s+x.precision,0)/scores.length,recall:scores.reduce((s,x)=>s+x.recall,0)/scores.length,f1:scores.reduce((s,x)=>s+x.f1,0)/scores.length}; }
export function completionRate(responses=[]) { return safeDivide(responses.filter((r)=>r.selectedActionId&&r.selectedJudgment).length,responses.length); }
export function calculateMetrics(responses=[]) { const recalls=recallByJudgment(responses),signal=aggregateSignalScores(responses); const times=responses.filter((r)=>!r.wasInterrupted).map((r)=>Number(r.activeResponseTimeMs??r.responseTimeMs)).filter((v)=>Number.isFinite(v)&&v>=0); const calibration=macroRecall(responses),action=actionAccuracy(responses),completeness=completionRate(responses),overall=calibration*.4+signal.f1*.25+action*.25+completeness*.1; return {actionAccuracy:action,judgmentMacroRecall:calibration,recallRisk:recalls.risk,recallInsufficient:recalls.insufficient,recallTrusted:recalls.trusted,trustedFalsePositiveRate:trustedFalsePositiveRate(responses),highConfidenceErrorRate:highConfidenceErrorRate(responses),signalPrecision:signal.precision,signalRecall:signal.recall,signalF1:signal.f1,completionRate:completeness,averageResponseTimeMs:times.length?times.reduce((s,v)=>s+v,0)/times.length:0,medianResponseTimeMs:median(times),overallScore:overall,sampleSize:responses.length}; }
export function formatPercent(value) { return `${Math.round((Number(value)||0)*100)}%`; }
